#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <cstring>
#include <iostream>
#include <iomanip>
#include <ctype.h>
#include <sys/stat.h>
#include <netinet/in.h>
#include <unistd.h>
#include <fcntl.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <limits.h>
#include <fstream>
#include <vector>
#include <openssl/evp.h>
#include <filesystem>
#include <algorithm>
#include <thread>
#include <mutex>
#include <shared_mutex>
#include <condition_variable>
#include <csignal>
#include <map>
#include <sstream>
#include <random>
#include <sys/time.h>
#include <chrono>
#include <execinfo.h>
#include <signal.h>