#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <cstring>
#include <iostream>
#include <iomanip>
#include <ctype.h>
#include <sys/stat.h>
#include <netinet/in.h>
#include <unistd.h>
#include <fcntl.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <limits.h>
#include <fstream>
#include <vector>
#include <openssl/evp.h>
#include <filesystem>
#include <algorithm>
#include <thread>
#include <csignal>